remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"

# Site Settings
locale: "ko-KR"
title: "Junyoung Oh"
subtitle: "Portfolio & Study Notes"
name: "Junyoung Oh"
description: "개인 포트폴리오, 프로젝트, 공부 정리"
url: "https://junyoung-five.github.io"
baseurl: ""

# Site Author
author:
  name: "Junyoung Oh"
  bio: "Robotics & Control"
  location: "South Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/junyoung-five"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:john.jy.oh@gmail.com"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  study:
    output: true
    permalink: /study/:path/

# Reading Files
encoding: "utf-8"
include:
  - _pages

# Build settings
markdown: kramdown
highlighter: rouge

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: false
  # _study
  - scope:
      path: ""
      type: study
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "study"
